services: 
  backend: 
    build: 
      context: ./backend
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    ports: 
      - "8000:8000"
    depends_on: 
      - database
    env_file: 
      - ./backend/.env

  frontend:
    build:
      context: frontend
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
      - react_build:/react/build
    env_file:
      - ./frontend/.env
    expose:
      - 3000
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend
    env_file:
      - ./nginx/.env

  database:
    image: postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    logging:
      driver: none
    env_file:
      - ./database/.env

volumes:
  postgres_data:
  react_build:
