# Generated by Django 4.0 on 2023-01-08 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of post', max_length=100)),
                ('body', models.TextField(help_text='Body of post', max_length=500)),
            ],
        ),
    ]
